ezplatform:
    system:
        default:
            content_view:
                full:
                    article:
                        controller: App\Controller\ReportController::showRootLocationPathStringAction
                        match:
                            Identifier\ContentType: [folder]
