ezplatform:
    system:
        default:
            content_view:
                full:
                    article:
                        controller: App\Controller\DefaultController::showSiteAccessNameAction
                        match:
                            Identifier\ContentType: [folder]
