services:
    app.command.test:
        class: AppBundle\Command\TestCommand
        arguments:
            $permissionResolver: '@=service("ezpublish.api.repository").getPermissionResolver()'
            $userService: '@ezpublish.api.service.user'
            $contentTypeService: '@ezpublish.api.service.content_type'
            $contentService: '@ezpublish.api.service.content'
            $locationService: '@ezpublish.api.service.location'
        tags:
            - { name: console.command }
